version: '3.7'

services:
  splitwise:
    image: shagunbandi/planmytrip:splitwise
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      POSTGRES_PRISMA_URL: ${POSTGRES_PRISMA_URL}
      POSTGRES_URL_NON_POOLING: ${POSTGRES_URL_NON_POOLING}
    env_file:
      - .env